// Augments the Env interface generated by `wrangler types` in
// worker-configuration.d.ts. Kept in a separate file deliberately: that file is
// regenerated wholesale by Wrangler, so anything added directly to it is lost
// on the next `npm run cf-typegen`.
//
// Email goes out through the Cloudflare Email Service `EMAIL` binding in
// wrangler.json. EMAIL_FROM is a plain var there; it must use one of the
// binding's allowed sender addresses (see ALLOWED_SENDERS in src/lib/email.ts).

declare namespace Cloudflare {
	interface Env {
		// send_email binding from wrangler.json.
		EMAIL?: SendEmail;
		EMAIL_FROM?: string;
		// Grok key for the admin reply drafter and the domain name inventor.
		XAI_API_KEY?: string;
	}
}
