// Augments the Env interface generated by `wrangler types` in
// worker-configuration.d.ts. Kept in a separate file deliberately: that file is
// regenerated wholesale by Wrangler, so anything added directly to it is lost
// on the next `npm run cf-typegen`.
//
// These two are set as Worker secrets, never committed:
//   npx wrangler secret put EMAIL_API_KEY
//   npx wrangler secret put EMAIL_FROM

declare namespace Cloudflare {
	interface Env {
		// Transactional email for order delivery. Without these the webhook can
		// mint a download link but has no way to send it to the customer.
		EMAIL_API_KEY?: string;
		EMAIL_FROM?: string;
		// Workers AI binding ("ai" in wrangler.json) used by /api/ai/generate.
		AI?: Ai;
		// Cloudflare Email Service binding ("send_email" in wrangler.json).
		EMAIL?: { send(message: { from: string; to: string; subject: string; html?: string; text?: string }): Promise<{ messageId: string }> };
	}
}
